application: wave-sommelier
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: wavesommelier.py
- url: /images
  static_dir: images
- url: /gadget
  static_dir: gadget
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /.*
  script: search.py
